#This is local jekyll for local rendering of edits, used by github for github pages. Use with: 'jekyll serve --config local_config.yml'
theme: "just-the-docs"
color_scheme: dark
heading_anchors: true
aux_links:
  "Heads on GitHub":
    - "https://github.com/linuxboot/heads"
aux_links_new_tab: true

title: Heads - Wiki

include: [Development/BOARDS_AND_TESTERS.md]

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/linuxboot/heads-wiki"
gh_edit_branch: "master"
gh_edit_view_mode: "edit"
